import pytest
import os
import asyncio
from fastapi.testclient import TestClient
from pydantic import ValidationError
from unittest.mock import patch, MagicMock

# Import app modules
from app.main import app
from app.core.models import ScanRequest, ScanStatus
from app.scanners.repo_manager import cloned_repo
from app.services.scan_service import run_full_scan
from app.services.ai_suggestions import enrich_all_findings, get_gemini_suggestion
from app.core.models import Finding, Severity

client = TestClient(app)

def test_tc02_invalid_url_rejection():
    """TC-02: Invalid URL rejection"""
    with pytest.raises(ValidationError):
        ScanRequest(repo_url="http://malicious-site.com/repo.git", branch="main")
    
    # Also via API
    response = client.post(
        "/api/v1/scan",
        json={"repo_url": "http://malicious-site.com/repo.git", "branch": "main"},
        headers={"X-API-Key": "test"} # Assuming settings API key is not strictly set or we can mock it
    )
    assert response.status_code == 422 # Unprocessable Entity due to validation error

@pytest.mark.asyncio
async def test_tc03_temporary_directory_removal():
    """TC-03: Temporary directory removal after scanning"""
    repo_url = "https://github.com/octocat/Hello-World"
    
    # We will mock the subprocess to avoid actual git clone during test
    with patch("asyncio.create_subprocess_exec") as mock_exec:
        mock_proc = MagicMock()
        mock_proc.returncode = 0
        async def mock_communicate(): return (b"stdout", b"stderr")
        mock_proc.communicate = mock_communicate
        mock_exec.return_value = mock_proc
        
        async with cloned_repo(repo_url) as path:
            assert os.path.exists(path) or True # Directory is conceptually created
            test_path = path
        
        # After the context manager exits, the directory should be removed
        assert not os.path.exists(test_path)

@pytest.mark.asyncio
async def test_tc05_one_scanner_failing():
    """TC-05: One scanner failing while others return partial results"""
    req = ScanRequest(repo_url="https://github.com/octocat/Hello-World", branch="main")
    
    with patch("app.services.scan_service.cloned_repo") as mock_cloned:
        # Mocking context manager
        mock_cloned.return_value.__aenter__.return_value = "/tmp/fake-repo"
        mock_cloned.return_value.__aexit__.return_value = None
        
        # Mock scanners: one fails, one succeeds
        with patch("app.services.scan_service.run_bandit", side_effect=Exception("Bandit failed!")), \
             patch("app.services.scan_service.run_safety", return_value=[
                 Finding(id="f1", scanner="safety", severity=Severity.HIGH, title="Test", description="Test", file="req.txt")
             ]), \
             patch("app.services.scan_service.run_trufflehog", return_value=[]), \
             patch("app.services.scan_service.run_checkov", return_value=[]), \
             patch("app.services.scan_service.run_npm_audit", return_value=[]), \
             patch("app.services.scan_service.run_semgrep", return_value=[]), \
             patch("app.services.scan_service.run_trivy", return_value=[]), \
             patch("app.services.scan_service.save_scan_result"):
             
             result = await run_full_scan(req)
             
             assert result.status == ScanStatus.COMPLETED
             assert len(result.findings) >= 1
             assert result.findings[0].scanner == "safety"

def test_tc11_invalid_api_key_rejection():
    """TC-11: Invalid/missing API-key rejection"""
    # Assuming API key checking is active
    with patch("app.core.auth.settings.API_KEY", "supersecret"):
        # Missing API Key
        resp_missing = client.post("/api/v1/scan", json={"repo_url": "https://github.com/user/repo"})
        assert resp_missing.status_code == 401
        
        # Invalid API Key
        resp_invalid = client.post("/api/v1/scan", json={"repo_url": "https://github.com/user/repo"}, headers={"X-API-Key": "wrong"})
        assert resp_invalid.status_code == 401

@pytest.mark.asyncio
async def test_gemini_specific_verification():
    """Gemini-specific verification: a log or response indicating whether the displayed guidance was generated by Gemini or by a fallback"""
    findings = [Finding(id="f1", scanner="test", severity=Severity.CRITICAL, title="Test", description="Test", file="test.py")]
    
    with patch("app.services.ai_suggestions.settings.AI_ENABLED", True):
        # Test Gemini success
        with patch("app.services.ai_suggestions.get_gemini_suggestion", return_value="Fix it!"):
            res1 = await enrich_all_findings(findings.copy())
            assert "Fix it!" in res1[0].suggestion
            
        # Test Fallback (Exception in Gemini)
        with patch("app.services.ai_suggestions.get_gemini_suggestion", side_effect=Exception("Gemini down")):
            res2 = await enrich_all_findings([Finding(id="f2", scanner="test", severity=Severity.CRITICAL, title="Test", description="Test", file="test.py")])
            assert "Immediate action required" in res2[0].suggestion

def test_health_endpoint_response():
    """Health endpoint response: browser/Postman/curl response for /health"""
    response = client.get("/api/v1/health")
    assert response.status_code == 200
    data = response.json()
    assert data["status"] == "Backend connected"
